services:
  database:
    image: mysql:8.0-debian
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  polaris-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    volumes:
      - ./backend:/back
    ports:
      - "9000:9000"  # Using 9000 because 8000 is busy
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  polaris-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5174" # Using 5174 because 5173 is busy
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    command: "npm run dev"
    volumes:
      - ./frontend:/front
      - /front/node_modules

volumes:
  mysql_data: