# Generated by Django 5.2.1 on 2025-06-09 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('network_type', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('5G', '5G'), ('LTE-Adv', 'LTE-Adv')], max_length=10)),
                ('signal_strength', models.FloatField(blank=True, null=True)),
                ('signal_quality', models.FloatField(blank=True, null=True)),
                ('cell_id', models.CharField(blank=True, max_length=100, null=True)),
                ('lac', models.CharField(blank=True, max_length=100, null=True)),
                ('tac', models.CharField(blank=True, max_length=100, null=True)),
                ('rac', models.CharField(blank=True, max_length=100, null=True)),
                ('plmn', models.CharField(blank=True, max_length=100, null=True)),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='mobile_reports.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='mobile_repo_device__0169e7_idx'), models.Index(fields=['latitude', 'longitude'], name='mobile_repo_latitud_29bc70_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('test_type', models.CharField(choices=[('HTTPD', 'HTTPD'), ('HTTPU', 'HTTPU'), ('PING', 'PING'), ('WEB', 'WEB'), ('DNS', 'DNS'), ('SMS', 'SMS')], max_length=10)),
                ('value', models.FloatField()),
                ('success', models.BooleanField()),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='mobile_reports.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='mobile_repo_device__dfa33e_idx')],
            },
        ),
    ]
