# Generated by Django 5.2.1 on 2025-06-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('network_type', models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('5G', '5G'), ('LTE-Adv', 'LTE-Adv'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('lac', models.CharField(blank=True, max_length=100, null=True)),
                ('tac', models.CharField(blank=True, max_length=100, null=True)),
                ('rac', models.CharField(blank=True, max_length=100, null=True)),
                ('cell_id', models.CharField(blank=True, max_length=100, null=True)),
                ('plmn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('arfcn', models.IntegerField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('frequency_band', models.CharField(blank=True, max_length=100, null=True)),
                ('rsrp', models.IntegerField(blank=True, null=True)),
                ('rsrq', models.IntegerField(blank=True, null=True)),
                ('rscp', models.IntegerField(blank=True, null=True)),
                ('ecIo', models.IntegerField(blank=True, null=True)),
                ('rxLev', models.IntegerField(blank=True, null=True)),
                ('ssRsrp', models.IntegerField(blank=True, null=True)),
                ('http_upload', models.FloatField()),
                ('http_download', models.FloatField()),
                ('ping_time', models.FloatField()),
                ('dns_response', models.IntegerField()),
                ('web_response', models.BigIntegerField()),
                ('sms_delivery_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='mobile_repo_user_id_eb544b_idx'), models.Index(fields=['latitude', 'longitude'], name='mobile_repo_latitud_29bc70_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('test_type', models.CharField(choices=[('HTTPD', 'HTTPD'), ('HTTPU', 'HTTPU'), ('PING', 'PING'), ('WEB', 'WEB'), ('DNS', 'DNS'), ('SMS', 'SMS')], max_length=10)),
                ('value', models.FloatField()),
                ('success', models.BooleanField()),
                ('additional_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_testResults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='mobile_repo_user_id_14bbd1_idx')],
            },
        ),
    ]
