# Generated by Django 5.0.7 on 2025-07-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_reports', '0002_alter_testresult_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='network_type',
            field=models.CharField(choices=[('GSM', 'GSM'), ('GPRS', 'GPRS'), ('EDGE', 'EDGE'), ('UMTS', 'UMTS'), ('HSPA', 'HSPA'), ('WCDMA', 'WCDMA'), ('3G', '3G'), ('HSPA+', 'HSPA+'), ('LTE', 'LTE'), ('5G', '5G'), ('LTE-Adv', 'LTE-Adv'), ('UNKNOWN', 'UNKNOWN')], max_length=10),
        ),
    ]
