# Generated by Django 5.0.7 on 2025-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_reports', '0003_alter_measurement_network_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='rac',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='ssRsrp',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='network_type',
            field=models.CharField(max_length=15),
        ),
    ]
