# Generated by Django 5.2.1 on 2025-06-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_usperuser_access',
            field=models.BooleanField(default=True),
        ),
    ]
