# Generated by Django 5.2.1 on 2025-06-12 20:10

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_allow_usperuser_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=users.models.name_generator, max_length=150, null=True),
        ),
    ]
